//! `manifest.csv` writer for the analysis corpus.
//!
//! Columns are pinned by `projects/A_1000_crate/README.md`:
//! `crate, version, license, downloads, sha256`. The manifest is the single
//! reproducibility artifact for the corpus — everything else under
//! `corpus/wild/` is regenerated by re-running the fetcher with the same
//! input and the same Sparse Index commit pin, so a missing or stale
//! manifest invalidates the run.
//!
//! No CSV-quoting layer is wired in: every value the fetcher emits is
//! known-comma-free (crate names are `[a-z0-9_-]+`, version strings are
//! SemVer, SPDX expressions never contain commas, downloads is a u64, the
//! sha256 column is lowercase hex). If a future column ever needs quoting,
//! switch to the `csv` crate.

use std::collections::HashSet;
use std::fs::OpenOptions;
use std::io::{self, BufWriter, Write};
use std::path::Path;

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ManifestRow {
    pub name: String,
    pub version: String,
    /// Empty when the crate did not declare a license. (We normally skip
    /// such crates upstream, but the column is reserved so a future "include
    /// missing-license crates and tag them" mode does not change the schema.)
    pub license: String,
    /// `None` when the fetch had no access to a downloads ranking source —
    /// e.g. when the input was a manual list rather than a crates.io DB
    /// dump. Rendered as an empty cell.
    pub downloads: Option<u64>,
    /// Lowercase hex SHA-256 of the original `.crate` tarball (matches the
    /// Sparse Index `cksum`).
    pub sha256: String,
}

pub const MANIFEST_HEADER: &str = "crate,version,license,downloads,sha256";

pub fn write_header<W: Write>(w: &mut W) -> io::Result<()> {
    writeln!(w, "{MANIFEST_HEADER}")
}

pub fn write_row<W: Write>(w: &mut W, row: &ManifestRow) -> io::Result<()> {
    writeln!(
        w,
        "{},{},{},{},{}",
        row.name,
        row.version,
        row.license,
        row.downloads.map(|d| d.to_string()).unwrap_or_default(),
        row.sha256,
    )
}

/// Parse a manifest CSV into rows. Strict on the 5-column shape: any
/// data line that does not split into exactly 5 cells is rejected as
/// [`io::ErrorKind::InvalidData`]. The header row, if present, is
/// recognised by its literal first cell `crate` and skipped.
///
/// `downloads` cells are parsed as `u64`; an empty cell maps to `None`,
/// matching the writer side.
///
/// Returns an empty Vec if the file does not exist, mirroring
/// [`read_manifest_names`].
pub fn read_manifest_rows(path: &Path) -> io::Result<Vec<ManifestRow>> {
    let body = match std::fs::read_to_string(path) {
        Ok(s) => s,
        Err(e) if e.kind() == io::ErrorKind::NotFound => return Ok(Vec::new()),
        Err(e) => return Err(e),
    };
    let mut out = Vec::new();
    for (lineno, line) in body.lines().enumerate() {
        let line = line.trim();
        if line.is_empty() {
            continue;
        }
        let parts: Vec<&str> = line.splitn(5, ',').collect();
        if parts.len() != 5 {
            return Err(io::Error::new(
                io::ErrorKind::InvalidData,
                format!(
                    "manifest line {}: expected 5 columns, got {}",
                    lineno + 1,
                    parts.len()
                ),
            ));
        }
        if lineno == 0 && parts[0] == "crate" && parts[1] == "version" {
            continue;
        }
        let downloads = if parts[3].is_empty() {
            None
        } else {
            Some(parts[3].parse::<u64>().map_err(|e| {
                io::Error::new(
                    io::ErrorKind::InvalidData,
                    format!("manifest line {}: invalid downloads: {}", lineno + 1, e),
                )
            })?)
        };
        out.push(ManifestRow {
            name: parts[0].to_string(),
            version: parts[1].to_string(),
            license: parts[2].to_string(),
            downloads,
            sha256: parts[4].to_string(),
        });
    }
    Ok(out)
}

/// Read the `crate` column of a manifest into a `HashSet`. Used by
/// `cntrdct fetch --resume` to skip crates that were already recorded by
/// a previous run.
///
/// Returns an empty set if the file does not exist; missing manifests are
/// the steady-state for a fresh corpus, not an error. Header rows are
/// recognised by their literal first cell `crate` and skipped. Any data
/// row without a comma is treated as malformed and triggers
/// [`io::ErrorKind::InvalidData`] — better to surface a corrupt manifest
/// loudly than to silently re-fetch crates that were already on disk.
pub fn read_manifest_names(path: &Path) -> io::Result<HashSet<String>> {
    let body = match std::fs::read_to_string(path) {
        Ok(s) => s,
        Err(e) if e.kind() == io::ErrorKind::NotFound => return Ok(HashSet::new()),
        Err(e) => return Err(e),
    };
    let mut out = HashSet::new();
    for (lineno, line) in body.lines().enumerate() {
        let line = line.trim();
        if line.is_empty() {
            continue;
        }
        let mut parts = line.splitn(2, ',');
        let first = parts
            .next()
            .ok_or_else(|| io::Error::new(io::ErrorKind::InvalidData, "empty line"))?;
        let _rest = parts.next().ok_or_else(|| {
            io::Error::new(
                io::ErrorKind::InvalidData,
                format!("manifest line {}: no comma", lineno + 1),
            )
        })?;
        if first == "crate" && lineno == 0 {
            continue;
        }
        out.insert(first.to_string());
    }
    Ok(out)
}

/// Append a row to `path`, writing the header first if the file does not
/// yet exist (or is empty). Suitable for streaming writes during a fetch
/// loop — the manifest stays well-formed even if the run aborts midway.
pub fn append_row(path: &Path, row: &ManifestRow) -> io::Result<()> {
    let needs_header = match std::fs::metadata(path) {
        Ok(m) => m.len() == 0,
        Err(e) if e.kind() == io::ErrorKind::NotFound => true,
        Err(e) => return Err(e),
    };
    if let Some(parent) = path.parent() {
        if !parent.as_os_str().is_empty() {
            std::fs::create_dir_all(parent)?;
        }
    }
    let file = OpenOptions::new().create(true).append(true).open(path)?;
    let mut buf = BufWriter::new(file);
    if needs_header {
        write_header(&mut buf)?;
    }
    write_row(&mut buf, row)?;
    buf.flush()
}

#[cfg(test)]
mod tests {
    use super::*;

    fn row(
        name: &str,
        version: &str,
        license: &str,
        downloads: Option<u64>,
        sha: &str,
    ) -> ManifestRow {
        ManifestRow {
            name: name.to_string(),
            version: version.to_string(),
            license: license.to_string(),
            downloads,
            sha256: sha.to_string(),
        }
    }

    #[test]
    fn header_matches_pinned_schema() {
        let mut buf = Vec::new();
        write_header(&mut buf).unwrap();
        assert_eq!(
            String::from_utf8(buf).unwrap(),
            "crate,version,license,downloads,sha256\n"
        );
    }

    #[test]
    fn row_with_downloads_renders_as_integer() {
        let mut buf = Vec::new();
        write_row(
            &mut buf,
            &row(
                "serde",
                "1.0.2",
                "MIT OR Apache-2.0",
                Some(1_234_567),
                "abc",
            ),
        )
        .unwrap();
        assert_eq!(
            String::from_utf8(buf).unwrap(),
            "serde,1.0.2,MIT OR Apache-2.0,1234567,abc\n"
        );
    }

    #[test]
    fn row_with_no_downloads_leaves_cell_empty() {
        let mut buf = Vec::new();
        write_row(
            &mut buf,
            &row("serde", "1.0.2", "MIT OR Apache-2.0", None, "abc"),
        )
        .unwrap();
        assert_eq!(
            String::from_utf8(buf).unwrap(),
            "serde,1.0.2,MIT OR Apache-2.0,,abc\n"
        );
    }

    #[test]
    fn append_row_creates_file_with_header_then_row() {
        let tmp = tempfile::tempdir().unwrap();
        let path = tmp.path().join("manifest.csv");
        append_row(&path, &row("a", "0.1.0", "MIT", None, "h1")).unwrap();
        let body = std::fs::read_to_string(&path).unwrap();
        assert_eq!(
            body,
            "crate,version,license,downloads,sha256\na,0.1.0,MIT,,h1\n"
        );
    }

    #[test]
    fn append_row_appends_without_re_emitting_header() {
        let tmp = tempfile::tempdir().unwrap();
        let path = tmp.path().join("manifest.csv");
        append_row(&path, &row("a", "0.1.0", "MIT", None, "h1")).unwrap();
        append_row(&path, &row("b", "0.2.0", "Apache-2.0", Some(42), "h2")).unwrap();
        let body = std::fs::read_to_string(&path).unwrap();
        assert_eq!(
            body,
            "crate,version,license,downloads,sha256\n\
             a,0.1.0,MIT,,h1\n\
             b,0.2.0,Apache-2.0,42,h2\n"
        );
    }

    #[test]
    fn append_row_creates_parent_directories() {
        let tmp = tempfile::tempdir().unwrap();
        let path = tmp.path().join("nested/dir/manifest.csv");
        append_row(&path, &row("a", "0.1.0", "MIT", None, "h1")).unwrap();
        assert!(path.exists());
    }

    #[test]
    fn read_manifest_names_returns_empty_for_missing_file() {
        let tmp = tempfile::tempdir().unwrap();
        let names = read_manifest_names(&tmp.path().join("absent.csv")).unwrap();
        assert!(names.is_empty());
    }

    #[test]
    fn read_manifest_names_collects_crate_column_skipping_header() {
        let tmp = tempfile::tempdir().unwrap();
        let path = tmp.path().join("manifest.csv");
        std::fs::write(
            &path,
            "crate,version,license,downloads,sha256\n\
             serde,1.0.2,MIT OR Apache-2.0,123,abc\n\
             log,0.4.20,MIT OR Apache-2.0,456,def\n",
        )
        .unwrap();
        let names = read_manifest_names(&path).unwrap();
        assert_eq!(names.len(), 2);
        assert!(names.contains("serde"));
        assert!(names.contains("log"));
    }

    #[test]
    fn read_manifest_names_rejects_lines_without_commas() {
        let tmp = tempfile::tempdir().unwrap();
        let path = tmp.path().join("manifest.csv");
        std::fs::write(&path, "crate,version,license,downloads,sha256\nbad-row\n").unwrap();
        let err = read_manifest_names(&path).unwrap_err();
        assert_eq!(err.kind(), io::ErrorKind::InvalidData);
    }

    #[test]
    fn read_manifest_rows_returns_empty_for_missing_file() {
        let tmp = tempfile::tempdir().unwrap();
        let rows = read_manifest_rows(&tmp.path().join("absent.csv")).unwrap();
        assert!(rows.is_empty());
    }

    #[test]
    fn read_manifest_rows_round_trip() {
        let tmp = tempfile::tempdir().unwrap();
        let path = tmp.path().join("manifest.csv");
        std::fs::write(
            &path,
            "crate,version,license,downloads,sha256\n\
             serde,1.0.228,MIT OR Apache-2.0,803456789,abc\n\
             log,0.4.20,MIT OR Apache-2.0,,def\n",
        )
        .unwrap();
        let rows = read_manifest_rows(&path).unwrap();
        assert_eq!(rows.len(), 2);
        assert_eq!(rows[0].name, "serde");
        assert_eq!(rows[0].version, "1.0.228");
        assert_eq!(rows[0].downloads, Some(803_456_789));
        assert_eq!(rows[0].sha256, "abc");
        assert_eq!(rows[1].name, "log");
        assert_eq!(rows[1].downloads, None);
    }

    #[test]
    fn read_manifest_rows_rejects_short_rows() {
        let tmp = tempfile::tempdir().unwrap();
        let path = tmp.path().join("manifest.csv");
        std::fs::write(
            &path,
            "crate,version,license,downloads,sha256\nserde,1.0.0,MIT\n",
        )
        .unwrap();
        let err = read_manifest_rows(&path).unwrap_err();
        assert_eq!(err.kind(), io::ErrorKind::InvalidData);
    }

    #[test]
    fn read_manifest_rows_rejects_bad_downloads() {
        let tmp = tempfile::tempdir().unwrap();
        let path = tmp.path().join("manifest.csv");
        std::fs::write(
            &path,
            "crate,version,license,downloads,sha256\nserde,1.0.0,MIT,not-a-number,abc\n",
        )
        .unwrap();
        let err = read_manifest_rows(&path).unwrap_err();
        assert_eq!(err.kind(), io::ErrorKind::InvalidData);
    }
}
