#!/usr/bin/env python3
"""
Fetch a curated set of Rust source files from crates.io and lay them
out under benchmarks/wild-corpus/ for the P-1 Rust wild corpus.

Each entry in CORPUS pins (crate_name, version, license_spdx, [files]).
For each entry the script:
  1. Looks up the canonical SHA-256 ("cksum") for that release in the
     sparse index at https://index.crates.io/<shard>/<crate>.
  2. Downloads the .crate tarball from
     https://crates.io/api/v1/crates/<crate>/<version>/download (which
     redirects to https://static.crates.io/crates/...). The script
     records the FINAL URL so provenance is unambiguous.
  3. Verifies the SHA-256 of the tarball against the value the sparse
     index reports. A mismatch is a hard fail.
  4. Extracts the listed `files` paths into
     benchmarks/wild-corpus/files/<flat_name>.rs.
  5. Prepends a 3-line provenance comment block (`// Source:`,
     `// License:`, `// Note:`) so the corpus is auditable. Rust
     line-comment syntax (NOT Python's `#`) is required so the
     cntrdct parser accepts the file.
  6. Emits / refreshes a manifest skeleton with `source`, `license`,
     `sha256` filled in. The maintainer fills in `expected: [...]`
     afterwards by running `cntrdct scan` and triaging findings.

Re-running the script is idempotent: the file content (header + body)
and recorded SHA-256 are deterministic for a pinned (crate, version,
file_path) triple. CI can therefore call this script and `git diff`
to detect drift.

Usage:
  python3 scripts/fetch_rust_corpus.py [--out benchmarks/wild-corpus] \\
      [--manifest-skeleton]

Environment:
  Network access to https://crates.io and https://index.crates.io. No
  third-party Python deps; uses stdlib `urllib`, `tarfile`, `hashlib`,
  `json`.
"""

from __future__ import annotations

import argparse
import hashlib
import io
import json
import sys
import tarfile
import urllib.request
from dataclasses import dataclass
from pathlib import Path
from typing import List, Tuple


@dataclass(frozen=True)
class CorpusEntry:
    """A single (crate, version) bundle and the files we vendor from it."""

    crate_name: str
    version: str
    license: str
    # (relative_path_inside_tarball, flat_name_for_corpus)
    files: Tuple[Tuple[str, str], ...]


# Allowlist. Pinned versions; permissive licenses only.
#
# Selection criteria:
# - License compatible with redistribution (MIT / BSD / Apache-2.0 /
#   ISC / Unlicense / Zlib, in any OR/AND combination).
# - Substantive Rust source (≥ ~5 KB total). Pure-FFI / generated-binding
#   crates (libc, windows-sys, web-sys, js-sys, *-sys, generated unicode
#   tables) are excluded — their signal value is poor.
# - Per crate, vendor src/lib.rs plus up to 7 substantive submodules,
#   ranked by file size. Skip files < 500 B and skip anything under
#   tests/, examples/, benches/, fuzz/, build.rs, src/bin/, generated
#   unicode_tables/, *_tests.rs, and tests.rs (these have different
#   code patterns that confuse the corpus signal).
# - Pinned (crate, version, file_path) triples make the output fully
#   deterministic across runs. CI can `git diff` to detect drift.
CORPUS: Tuple[CorpusEntry, ...] = (
    CorpusEntry(
        crate_name="syn",
        version="2.0.117",
        license="MIT OR Apache-2.0",
        # syn's `src/gen/*.rs` files are auto-generated visitor /
        # fold / debug / eq trait impls (header line `// This file
        # is @generated by syn-internal-codegen.`). They produce
        # ~290 clone-drift findings between them on the v0 scan
        # because every method body is structurally identical, and
        # ALL of those findings are FPs by construction. Mirroring
        # the Python wild-corpus exclusion of `idna_uts46data.py`
        # (a Unicode lookup table). Excluded.
        files=(
            ("syn-2.0.117/src/lib.rs", "syn__lib.rs"),
            ("syn-2.0.117/src/expr.rs", "syn__expr.rs"),
            ("syn-2.0.117/src/item.rs", "syn__item.rs"),
        ),
    ),
    CorpusEntry(
        crate_name="hashbrown",
        version="0.17.0",
        license="MIT OR Apache-2.0",
        files=(
            ("hashbrown-0.17.0/src/lib.rs", "hashbrown__lib.rs"),
            ("hashbrown-0.17.0/src/map.rs", "hashbrown__map.rs"),
            ("hashbrown-0.17.0/src/raw.rs", "hashbrown__raw.rs"),
            ("hashbrown-0.17.0/src/table.rs", "hashbrown__table.rs"),
            ("hashbrown-0.17.0/src/set.rs", "hashbrown__set.rs"),
            ("hashbrown-0.17.0/src/raw_entry.rs", "hashbrown__raw_entry.rs"),
            ("hashbrown-0.17.0/src/external_trait_impls/rayon/map.rs", "hashbrown__external_trait_impls_rayon_map.rs"),
            ("hashbrown-0.17.0/src/external_trait_impls/rayon/set.rs", "hashbrown__external_trait_impls_rayon_set.rs"),
        ),
    ),
    CorpusEntry(
        crate_name="bitflags",
        version="2.11.1",
        license="MIT OR Apache-2.0",
        files=(
            ("bitflags-2.11.1/src/lib.rs", "bitflags__lib.rs"),
            ("bitflags-2.11.1/src/public.rs", "bitflags__public.rs"),
            ("bitflags-2.11.1/src/traits.rs", "bitflags__traits.rs"),
            ("bitflags-2.11.1/src/parser.rs", "bitflags__parser.rs"),
            ("bitflags-2.11.1/src/external.rs", "bitflags__external.rs"),
            ("bitflags-2.11.1/src/iter.rs", "bitflags__iter.rs"),
            ("bitflags-2.11.1/src/internal.rs", "bitflags__internal.rs"),
            ("bitflags-2.11.1/src/external/serde.rs", "bitflags__external_serde.rs"),
        ),
    ),
    CorpusEntry(
        crate_name="base64",
        version="0.22.1",
        license="MIT OR Apache-2.0",
        files=(
            ("base64-0.22.1/src/lib.rs", "base64__lib.rs"),
            ("base64-0.22.1/src/engine/mod.rs", "base64__engine_mod.rs"),
            ("base64-0.22.1/src/write/encoder.rs", "base64__write_encoder.rs"),
            ("base64-0.22.1/src/encode.rs", "base64__encode.rs"),
            ("base64-0.22.1/src/engine/general_purpose/mod.rs", "base64__engine_general_purpose_mod.rs"),
            ("base64-0.22.1/src/read/decoder.rs", "base64__read_decoder.rs"),
            ("base64-0.22.1/src/decode.rs", "base64__decode.rs"),
            ("base64-0.22.1/src/engine/general_purpose/decode.rs", "base64__engine_general_purpose_decode.rs"),
        ),
    ),
    CorpusEntry(
        crate_name="regex-syntax",
        version="0.8.10",
        license="MIT OR Apache-2.0",
        files=(
            ("regex-syntax-0.8.10/src/lib.rs", "regex_syntax__lib.rs"),
            ("regex-syntax-0.8.10/src/ast/parse.rs", "regex_syntax__ast_parse.rs"),
            ("regex-syntax-0.8.10/src/hir/mod.rs", "regex_syntax__hir_mod.rs"),
            ("regex-syntax-0.8.10/src/hir/translate.rs", "regex_syntax__hir_translate.rs"),
            ("regex-syntax-0.8.10/src/hir/literal.rs", "regex_syntax__hir_literal.rs"),
            ("regex-syntax-0.8.10/src/ast/mod.rs", "regex_syntax__ast_mod.rs"),
            ("regex-syntax-0.8.10/src/unicode.rs", "regex_syntax__unicode.rs"),
            ("regex-syntax-0.8.10/src/hir/print.rs", "regex_syntax__hir_print.rs"),
        ),
    ),
    CorpusEntry(
        crate_name="indexmap",
        version="2.14.0",
        license="Apache-2.0 OR MIT",
        files=(
            ("indexmap-2.14.0/src/lib.rs", "indexmap__lib.rs"),
            ("indexmap-2.14.0/src/map.rs", "indexmap__map.rs"),
            ("indexmap-2.14.0/src/set.rs", "indexmap__set.rs"),
            ("indexmap-2.14.0/src/map/slice.rs", "indexmap__map_slice.rs"),
            ("indexmap-2.14.0/src/inner.rs", "indexmap__inner.rs"),
            ("indexmap-2.14.0/src/map/raw_entry_v1.rs", "indexmap__map_raw_entry_v1.rs"),
            ("indexmap-2.14.0/src/map/iter.rs", "indexmap__map_iter.rs"),
            ("indexmap-2.14.0/src/rayon/set.rs", "indexmap__rayon_set.rs"),
        ),
    ),
    CorpusEntry(
        crate_name="itertools",
        version="0.14.0",
        license="MIT OR Apache-2.0",
        files=(
            ("itertools-0.14.0/src/lib.rs", "itertools__lib.rs"),
            ("itertools-0.14.0/src/adaptors/mod.rs", "itertools__adaptors_mod.rs"),
            ("itertools-0.14.0/src/grouping_map.rs", "itertools__grouping_map.rs"),
            ("itertools-0.14.0/src/either_or_both.rs", "itertools__either_or_both.rs"),
            ("itertools-0.14.0/src/groupbylazy.rs", "itertools__groupbylazy.rs"),
            ("itertools-0.14.0/src/tuple_impl.rs", "itertools__tuple_impl.rs"),
            ("itertools-0.14.0/src/merge_join.rs", "itertools__merge_join.rs"),
            ("itertools-0.14.0/src/combinations.rs", "itertools__combinations.rs"),
        ),
    ),
    CorpusEntry(
        crate_name="serde",
        version="1.0.228",
        license="MIT OR Apache-2.0",
        files=(
            ("serde-1.0.228/src/lib.rs", "serde__lib.rs"),
            ("serde-1.0.228/src/private/de.rs", "serde__private_de.rs"),
            ("serde-1.0.228/src/core/de/impls.rs", "serde__core_de_impls.rs"),
            ("serde-1.0.228/src/core/de/mod.rs", "serde__core_de_mod.rs"),
            ("serde-1.0.228/src/core/ser/mod.rs", "serde__core_ser_mod.rs"),
            ("serde-1.0.228/src/core/de/value.rs", "serde__core_de_value.rs"),
            ("serde-1.0.228/src/private/ser.rs", "serde__private_ser.rs"),
            ("serde-1.0.228/src/core/ser/impls.rs", "serde__core_ser_impls.rs"),
        ),
    ),
    CorpusEntry(
        crate_name="thiserror",
        version="2.0.18",
        license="MIT OR Apache-2.0",
        files=(
            ("thiserror-2.0.18/src/lib.rs", "thiserror__lib.rs"),
            ("thiserror-2.0.18/src/display.rs", "thiserror__display.rs"),
            ("thiserror-2.0.18/src/aserror.rs", "thiserror__aserror.rs"),
        ),
    ),
    CorpusEntry(
        crate_name="memchr",
        version="2.8.0",
        license="Unlicense OR MIT",
        files=(
            ("memchr-2.8.0/src/lib.rs", "memchr__lib.rs"),
            ("memchr-2.8.0/src/arch/x86_64/avx2/memchr.rs", "memchr__arch_x86_64_avx2_memchr.rs"),
            ("memchr-2.8.0/src/arch/generic/memchr.rs", "memchr__arch_generic_memchr.rs"),
            ("memchr-2.8.0/src/arch/x86_64/sse2/memchr.rs", "memchr__arch_x86_64_sse2_memchr.rs"),
            ("memchr-2.8.0/src/memmem/searcher.rs", "memchr__memmem_searcher.rs"),
            ("memchr-2.8.0/src/arch/aarch64/neon/memchr.rs", "memchr__arch_aarch64_neon_memchr.rs"),
            ("memchr-2.8.0/src/arch/all/memchr.rs", "memchr__arch_all_memchr.rs"),
            ("memchr-2.8.0/src/arch/wasm32/simd128/memchr.rs", "memchr__arch_wasm32_simd128_memchr.rs"),
        ),
    ),
    CorpusEntry(
        crate_name="serde_json",
        version="1.0.149",
        license="MIT OR Apache-2.0",
        files=(
            ("serde_json-1.0.149/src/lib.rs", "serde_json__lib.rs"),
            ("serde_json-1.0.149/src/de.rs", "serde_json__de.rs"),
            ("serde_json-1.0.149/src/ser.rs", "serde_json__ser.rs"),
            ("serde_json-1.0.149/src/value/de.rs", "serde_json__value_de.rs"),
            ("serde_json-1.0.149/src/map.rs", "serde_json__map.rs"),
            ("serde_json-1.0.149/src/read.rs", "serde_json__read.rs"),
            ("serde_json-1.0.149/src/value/mod.rs", "serde_json__value_mod.rs"),
            ("serde_json-1.0.149/src/value/ser.rs", "serde_json__value_ser.rs"),
        ),
    ),
    CorpusEntry(
        crate_name="regex-automata",
        version="0.4.14",
        license="MIT OR Apache-2.0",
        files=(
            ("regex-automata-0.4.14/src/lib.rs", "regex_automata__lib.rs"),
            ("regex-automata-0.4.14/src/dfa/dense.rs", "regex_automata__dfa_dense.rs"),
            ("regex-automata-0.4.14/src/hybrid/dfa.rs", "regex_automata__hybrid_dfa.rs"),
            ("regex-automata-0.4.14/src/meta/regex.rs", "regex_automata__meta_regex.rs"),
            ("regex-automata-0.4.14/src/dfa/onepass.rs", "regex_automata__dfa_onepass.rs"),
            ("regex-automata-0.4.14/src/dfa/sparse.rs", "regex_automata__dfa_sparse.rs"),
            ("regex-automata-0.4.14/src/util/captures.rs", "regex_automata__util_captures.rs"),
            ("regex-automata-0.4.14/src/util/look.rs", "regex_automata__util_look.rs"),
        ),
    ),
    CorpusEntry(
        crate_name="once_cell",
        version="1.21.4",
        license="MIT OR Apache-2.0",
        files=(
            ("once_cell-1.21.4/src/lib.rs", "once_cell__lib.rs"),
            ("once_cell-1.21.4/src/race.rs", "once_cell__race.rs"),
            ("once_cell-1.21.4/src/imp_std.rs", "once_cell__imp_std.rs"),
            ("once_cell-1.21.4/src/imp_pl.rs", "once_cell__imp_pl.rs"),
            ("once_cell-1.21.4/src/imp_cs.rs", "once_cell__imp_cs.rs"),
        ),
    ),
    CorpusEntry(
        crate_name="regex",
        version="1.12.3",
        license="MIT OR Apache-2.0",
        files=(
            ("regex-1.12.3/src/lib.rs", "regex__lib.rs"),
            ("regex-1.12.3/src/builders.rs", "regex__builders.rs"),
            ("regex-1.12.3/src/regex/bytes.rs", "regex__regex_bytes.rs"),
            ("regex-1.12.3/src/regex/string.rs", "regex__regex_string.rs"),
            ("regex-1.12.3/src/regexset/bytes.rs", "regex__regexset_bytes.rs"),
            ("regex-1.12.3/src/regexset/string.rs", "regex__regexset_string.rs"),
            ("regex-1.12.3/src/error.rs", "regex__error.rs"),
            ("regex-1.12.3/src/bytes.rs", "regex__bytes.rs"),
        ),
    ),
    CorpusEntry(
        crate_name="clap",
        version="4.6.1",
        license="MIT OR Apache-2.0",
        files=(
            ("clap-4.6.1/src/lib.rs", "clap__lib.rs"),
            ("clap-4.6.1/src/_derive/mod.rs", "clap___derive_mod.rs"),
            ("clap-4.6.1/src/_derive/_tutorial.rs", "clap___derive__tutorial.rs"),
            ("clap-4.6.1/src/_tutorial.rs", "clap___tutorial.rs"),
            ("clap-4.6.1/src/_faq.rs", "clap___faq.rs"),
            ("clap-4.6.1/src/_concepts.rs", "clap___concepts.rs"),
            ("clap-4.6.1/src/_features.rs", "clap___features.rs"),
            ("clap-4.6.1/src/_cookbook/mod.rs", "clap___cookbook_mod.rs"),
        ),
    ),
    CorpusEntry(
        crate_name="aho-corasick",
        version="1.1.4",
        license="Unlicense OR MIT",
        files=(
            ("aho-corasick-1.1.4/src/lib.rs", "aho_corasick__lib.rs"),
            ("aho-corasick-1.1.4/src/ahocorasick.rs", "aho_corasick__ahocorasick.rs"),
            ("aho-corasick-1.1.4/src/nfa/noncontiguous.rs", "aho_corasick__nfa_noncontiguous.rs"),
            ("aho-corasick-1.1.4/src/automaton.rs", "aho_corasick__automaton.rs"),
            ("aho-corasick-1.1.4/src/packed/vector.rs", "aho_corasick__packed_vector.rs"),
            ("aho-corasick-1.1.4/src/packed/teddy/generic.rs", "aho_corasick__packed_teddy_generic.rs"),
            ("aho-corasick-1.1.4/src/nfa/contiguous.rs", "aho_corasick__nfa_contiguous.rs"),
            ("aho-corasick-1.1.4/src/util/search.rs", "aho_corasick__util_search.rs"),
        ),
    ),
    CorpusEntry(
        crate_name="parking_lot_core",
        version="0.9.12",
        license="MIT OR Apache-2.0",
        files=(
            ("parking_lot_core-0.9.12/src/lib.rs", "parking_lot_core__lib.rs"),
            ("parking_lot_core-0.9.12/src/parking_lot.rs", "parking_lot_core__parking_lot.rs"),
            ("parking_lot_core-0.9.12/src/word_lock.rs", "parking_lot_core__word_lock.rs"),
            ("parking_lot_core-0.9.12/src/thread_parker/unix.rs", "parking_lot_core__thread_parker_unix.rs"),
            ("parking_lot_core-0.9.12/src/thread_parker/windows/keyed_event.rs", "parking_lot_core__thread_parker_windows_keyed_event.rs"),
            ("parking_lot_core-0.9.12/src/thread_parker/windows/mod.rs", "parking_lot_core__thread_parker_windows_mod.rs"),
            ("parking_lot_core-0.9.12/src/thread_parker/linux.rs", "parking_lot_core__thread_parker_linux.rs"),
            ("parking_lot_core-0.9.12/src/thread_parker/windows/waitaddress.rs", "parking_lot_core__thread_parker_windows_waitaddress.rs"),
        ),
    ),
    CorpusEntry(
        crate_name="semver",
        version="1.0.28",
        license="MIT OR Apache-2.0",
        files=(
            ("semver-1.0.28/src/lib.rs", "semver__lib.rs"),
            ("semver-1.0.28/src/identifier.rs", "semver__identifier.rs"),
            ("semver-1.0.28/src/parse.rs", "semver__parse.rs"),
            ("semver-1.0.28/src/impls.rs", "semver__impls.rs"),
            ("semver-1.0.28/src/display.rs", "semver__display.rs"),
            ("semver-1.0.28/src/eval.rs", "semver__eval.rs"),
            ("semver-1.0.28/src/error.rs", "semver__error.rs"),
            ("semver-1.0.28/src/serde.rs", "semver__serde.rs"),
        ),
    ),
    CorpusEntry(
        crate_name="mio",
        version="1.2.0",
        license="MIT",
        files=(
            ("mio-1.2.0/src/lib.rs", "mio__lib.rs"),
            ("mio-1.2.0/src/sys/windows/named_pipe.rs", "mio__sys_windows_named_pipe.rs"),
            ("mio-1.2.0/src/poll.rs", "mio__poll.rs"),
            ("mio-1.2.0/src/sys/unix/selector/kqueue.rs", "mio__sys_unix_selector_kqueue.rs"),
            ("mio-1.2.0/src/net/udp.rs", "mio__net_udp.rs"),
            ("mio-1.2.0/src/sys/unix/selector/poll.rs", "mio__sys_unix_selector_poll.rs"),
            ("mio-1.2.0/src/sys/windows/selector.rs", "mio__sys_windows_selector.rs"),
            ("mio-1.2.0/src/sys/unix/pipe.rs", "mio__sys_unix_pipe.rs"),
        ),
    ),
    CorpusEntry(
        crate_name="idna",
        version="1.1.0",
        license="MIT OR Apache-2.0",
        files=(
            ("idna-1.1.0/src/lib.rs", "idna__lib.rs"),
            ("idna-1.1.0/src/uts46.rs", "idna__uts46.rs"),
            ("idna-1.1.0/src/punycode.rs", "idna__punycode.rs"),
            ("idna-1.1.0/src/deprecated.rs", "idna__deprecated.rs"),
        ),
    ),
    CorpusEntry(
        crate_name="http",
        version="1.4.0",
        license="MIT OR Apache-2.0",
        files=(
            ("http-1.4.0/src/lib.rs", "http__lib.rs"),
            ("http-1.4.0/src/header/map.rs", "http__header_map.rs"),
            ("http-1.4.0/src/header/name.rs", "http__header_name.rs"),
            ("http-1.4.0/src/uri/mod.rs", "http__uri_mod.rs"),
            ("http-1.4.0/src/request.rs", "http__request.rs"),
            ("http-1.4.0/src/status.rs", "http__status.rs"),
            ("http-1.4.0/src/uri/authority.rs", "http__uri_authority.rs"),
            ("http-1.4.0/src/response.rs", "http__response.rs"),
        ),
    ),
    CorpusEntry(
        crate_name="time",
        version="0.3.47",
        license="MIT OR Apache-2.0",
        files=(
            ("time-0.3.47/src/lib.rs", "time__lib.rs"),
            ("time-0.3.47/src/duration.rs", "time__duration.rs"),
            ("time-0.3.47/src/offset_date_time.rs", "time__offset_date_time.rs"),
            ("time-0.3.47/src/date.rs", "time__date.rs"),
            ("time-0.3.47/src/utc_date_time.rs", "time__utc_date_time.rs"),
            ("time-0.3.47/src/parsing/parsed.rs", "time__parsing_parsed.rs"),
            ("time-0.3.47/src/primitive_date_time.rs", "time__primitive_date_time.rs"),
            ("time-0.3.47/src/time.rs", "time__time.rs"),
        ),
    ),
    CorpusEntry(
        crate_name="hyper",
        version="1.9.0",
        license="MIT",
        files=(
            ("hyper-1.9.0/src/lib.rs", "hyper__lib.rs"),
            ("hyper-1.9.0/src/proto/h1/role.rs", "hyper__proto_h1_role.rs"),
            ("hyper-1.9.0/src/proto/h1/conn.rs", "hyper__proto_h1_conn.rs"),
            ("hyper-1.9.0/src/proto/h1/decode.rs", "hyper__proto_h1_decode.rs"),
            ("hyper-1.9.0/src/proto/h1/io.rs", "hyper__proto_h1_io.rs"),
            ("hyper-1.9.0/src/proto/h1/dispatch.rs", "hyper__proto_h1_dispatch.rs"),
            ("hyper-1.9.0/src/proto/h2/client.rs", "hyper__proto_h2_client.rs"),
            ("hyper-1.9.0/src/ffi/http_types.rs", "hyper__ffi_http_types.rs"),
        ),
    ),
    CorpusEntry(
        crate_name="rustls",
        version="0.23.40",
        license="Apache-2.0 OR ISC OR MIT",
        files=(
            ("rustls-0.23.40/src/lib.rs", "rustls__lib.rs"),
            ("rustls-0.23.40/src/msgs/handshake.rs", "rustls__msgs_handshake.rs"),
            ("rustls-0.23.40/src/client/tls13.rs", "rustls__client_tls13.rs"),
            ("rustls-0.23.40/src/server/tls13.rs", "rustls__server_tls13.rs"),
            ("rustls-0.23.40/src/error.rs", "rustls__error.rs"),
            ("rustls-0.23.40/src/conn.rs", "rustls__conn.rs"),
            ("rustls-0.23.40/src/server/server_conn.rs", "rustls__server_server_conn.rs"),
            ("rustls-0.23.40/src/client/tls12.rs", "rustls__client_tls12.rs"),
        ),
    ),
    CorpusEntry(
        crate_name="url",
        version="2.5.8",
        license="MIT OR Apache-2.0",
        files=(
            ("url-2.5.8/src/lib.rs", "url__lib.rs"),
            ("url-2.5.8/src/parser.rs", "url__parser.rs"),
            ("url-2.5.8/src/host.rs", "url__host.rs"),
            ("url-2.5.8/src/quirks.rs", "url__quirks.rs"),
            ("url-2.5.8/src/path_segments.rs", "url__path_segments.rs"),
            ("url-2.5.8/src/slicing.rs", "url__slicing.rs"),
            ("url-2.5.8/src/origin.rs", "url__origin.rs"),
        ),
    ),
    CorpusEntry(
        crate_name="toml",
        version="1.1.2+spec-1.1.0",
        license="MIT OR Apache-2.0",
        files=(
            ("toml-1.1.2+spec-1.1.0/src/lib.rs", "toml__lib.rs"),
            ("toml-1.1.2+spec-1.1.0/src/value.rs", "toml__value.rs"),
            ("toml-1.1.2+spec-1.1.0/src/macros.rs", "toml__macros.rs"),
            ("toml-1.1.2+spec-1.1.0/src/de/parser/document.rs", "toml__de_parser_document.rs"),
            ("toml-1.1.2+spec-1.1.0/src/map.rs", "toml__map.rs"),
            ("toml-1.1.2+spec-1.1.0/src/ser/value/map.rs", "toml__ser_value_map.rs"),
            ("toml-1.1.2+spec-1.1.0/src/table.rs", "toml__table.rs"),
            ("toml-1.1.2+spec-1.1.0/src/de/parser/devalue.rs", "toml__de_parser_devalue.rs"),
        ),
    ),
    CorpusEntry(
        crate_name="toml_edit",
        version="0.25.11+spec-1.1.0",
        license="MIT OR Apache-2.0",
        files=(
            ("toml_edit-0.25.11+spec-1.1.0/src/lib.rs", "toml_edit__lib.rs"),
            ("toml_edit-0.25.11+spec-1.1.0/src/table.rs", "toml_edit__table.rs"),
            ("toml_edit-0.25.11+spec-1.1.0/src/parser/document.rs", "toml_edit__parser_document.rs"),
            ("toml_edit-0.25.11+spec-1.1.0/src/encode.rs", "toml_edit__encode.rs"),
            ("toml_edit-0.25.11+spec-1.1.0/src/item.rs", "toml_edit__item.rs"),
            ("toml_edit-0.25.11+spec-1.1.0/src/array.rs", "toml_edit__array.rs"),
            ("toml_edit-0.25.11+spec-1.1.0/src/ser/map.rs", "toml_edit__ser_map.rs"),
            ("toml_edit-0.25.11+spec-1.1.0/src/value.rs", "toml_edit__value.rs"),
        ),
    ),
    CorpusEntry(
        crate_name="chrono",
        version="0.4.44",
        license="MIT OR Apache-2.0",
        files=(
            ("chrono-0.4.44/src/lib.rs", "chrono__lib.rs"),
            ("chrono-0.4.44/src/format/parse.rs", "chrono__format_parse.rs"),
            ("chrono-0.4.44/src/naive/date/mod.rs", "chrono__naive_date_mod.rs"),
            ("chrono-0.4.44/src/naive/datetime/mod.rs", "chrono__naive_datetime_mod.rs"),
            ("chrono-0.4.44/src/format/parsed.rs", "chrono__format_parsed.rs"),
            ("chrono-0.4.44/src/datetime/mod.rs", "chrono__datetime_mod.rs"),
            ("chrono-0.4.44/src/naive/time/mod.rs", "chrono__naive_time_mod.rs"),
            ("chrono-0.4.44/src/time_delta.rs", "chrono__time_delta.rs"),
        ),
    ),
    CorpusEntry(
        crate_name="uuid",
        version="1.23.1",
        license="Apache-2.0 OR MIT",
        files=(
            ("uuid-1.23.1/src/lib.rs", "uuid__lib.rs"),
            ("uuid-1.23.1/src/timestamp.rs", "uuid__timestamp.rs"),
            ("uuid-1.23.1/src/fmt.rs", "uuid__fmt.rs"),
            ("uuid-1.23.1/src/external/serde_support.rs", "uuid__external_serde_support.rs"),
            ("uuid-1.23.1/src/builder.rs", "uuid__builder.rs"),
            ("uuid-1.23.1/src/parser.rs", "uuid__parser.rs"),
            ("uuid-1.23.1/src/rng.rs", "uuid__rng.rs"),
            ("uuid-1.23.1/src/v7.rs", "uuid__v7.rs"),
        ),
    ),
    CorpusEntry(
        crate_name="winnow",
        version="1.0.2",
        license="MIT",
        files=(
            ("winnow-1.0.2/src/lib.rs", "winnow__lib.rs"),
            ("winnow-1.0.2/src/binary/mod.rs", "winnow__binary_mod.rs"),
            ("winnow-1.0.2/src/ascii/mod.rs", "winnow__ascii_mod.rs"),
            ("winnow-1.0.2/src/stream/mod.rs", "winnow__stream_mod.rs"),
            ("winnow-1.0.2/src/combinator/multi.rs", "winnow__combinator_multi.rs"),
            ("winnow-1.0.2/src/parser.rs", "winnow__parser.rs"),
            ("winnow-1.0.2/src/error.rs", "winnow__error.rs"),
            ("winnow-1.0.2/src/token/mod.rs", "winnow__token_mod.rs"),
        ),
    ),
    CorpusEntry(
        crate_name="flate2",
        version="1.1.9",
        license="MIT OR Apache-2.0",
        files=(
            ("flate2-1.1.9/src/lib.rs", "flate2__lib.rs"),
            ("flate2-1.1.9/src/mem.rs", "flate2__mem.rs"),
            ("flate2-1.1.9/src/gz/mod.rs", "flate2__gz_mod.rs"),
            ("flate2-1.1.9/src/gz/write.rs", "flate2__gz_write.rs"),
            ("flate2-1.1.9/src/ffi/c.rs", "flate2__ffi_c.rs"),
            ("flate2-1.1.9/src/gz/bufread.rs", "flate2__gz_bufread.rs"),
            ("flate2-1.1.9/src/zlib/write.rs", "flate2__zlib_write.rs"),
            ("flate2-1.1.9/src/deflate/write.rs", "flate2__deflate_write.rs"),
        ),
    ),
    CorpusEntry(
        crate_name="tracing-subscriber",
        version="0.3.23",
        license="MIT",
        files=(
            ("tracing-subscriber-0.3.23/src/lib.rs", "tracing_subscriber__lib.rs"),
            ("tracing-subscriber-0.3.23/src/fmt/format/mod.rs", "tracing_subscriber__fmt_format_mod.rs"),
            ("tracing-subscriber-0.3.23/src/layer/mod.rs", "tracing_subscriber__layer_mod.rs"),
            ("tracing-subscriber-0.3.23/src/fmt/fmt_layer.rs", "tracing_subscriber__fmt_fmt_layer.rs"),
            ("tracing-subscriber-0.3.23/src/filter/layer_filters/mod.rs", "tracing_subscriber__filter_layer_filters_mod.rs"),
            ("tracing-subscriber-0.3.23/src/fmt/mod.rs", "tracing_subscriber__fmt_mod.rs"),
            ("tracing-subscriber-0.3.23/src/fmt/writer.rs", "tracing_subscriber__fmt_writer.rs"),
            ("tracing-subscriber-0.3.23/src/fmt/format/json.rs", "tracing_subscriber__fmt_format_json.rs"),
        ),
    ),
    CorpusEntry(
        crate_name="object",
        version="0.39.1",
        license="Apache-2.0 OR MIT",
        files=(
            ("object-0.39.1/src/lib.rs", "object__lib.rs"),
            ("object-0.39.1/src/elf.rs", "object__elf.rs"),
            ("object-0.39.1/src/macho.rs", "object__macho.rs"),
            ("object-0.39.1/src/build/elf.rs", "object__build_elf.rs"),
            ("object-0.39.1/src/pe.rs", "object__pe.rs"),
            ("object-0.39.1/src/write/elf/writer.rs", "object__write_elf_writer.rs"),
            ("object-0.39.1/src/read/any.rs", "object__read_any.rs"),
            ("object-0.39.1/src/write/macho.rs", "object__write_macho.rs"),
        ),
    ),
    CorpusEntry(
        crate_name="h2",
        version="0.4.14",
        license="MIT",
        files=(
            ("h2-0.4.14/src/lib.rs", "h2__lib.rs"),
            ("h2-0.4.14/src/server.rs", "h2__server.rs"),
            ("h2-0.4.14/src/client.rs", "h2__client.rs"),
            ("h2-0.4.14/src/proto/streams/streams.rs", "h2__proto_streams_streams.rs"),
            ("h2-0.4.14/src/proto/streams/recv.rs", "h2__proto_streams_recv.rs"),
            ("h2-0.4.14/src/proto/streams/prioritize.rs", "h2__proto_streams_prioritize.rs"),
            ("h2-0.4.14/src/frame/headers.rs", "h2__frame_headers.rs"),
            ("h2-0.4.14/src/hpack/decoder.rs", "h2__hpack_decoder.rs"),
        ),
    ),
    CorpusEntry(
        crate_name="nom",
        version="8.0.0",
        license="MIT",
        files=(
            ("nom-8.0.0/src/lib.rs", "nom__lib.rs"),
            ("nom-8.0.0/src/number/streaming.rs", "nom__number_streaming.rs"),
            ("nom-8.0.0/src/number/complete.rs", "nom__number_complete.rs"),
            ("nom-8.0.0/src/multi/mod.rs", "nom__multi_mod.rs"),
            ("nom-8.0.0/src/number/mod.rs", "nom__number_mod.rs"),
            ("nom-8.0.0/src/character/streaming.rs", "nom__character_streaming.rs"),
            ("nom-8.0.0/src/character/complete.rs", "nom__character_complete.rs"),
            ("nom-8.0.0/src/traits.rs", "nom__traits.rs"),
        ),
    ),
    CorpusEntry(
        crate_name="clap_builder",
        version="4.6.0",
        license="MIT OR Apache-2.0",
        files=(
            ("clap_builder-4.6.0/src/lib.rs", "clap_builder__lib.rs"),
            ("clap_builder-4.6.0/src/builder/command.rs", "clap_builder__builder_command.rs"),
            ("clap_builder-4.6.0/src/builder/arg.rs", "clap_builder__builder_arg.rs"),
            ("clap_builder-4.6.0/src/builder/value_parser.rs", "clap_builder__builder_value_parser.rs"),
            ("clap_builder-4.6.0/src/parser/matches/arg_matches.rs", "clap_builder__parser_matches_arg_matches.rs"),
            ("clap_builder-4.6.0/src/parser/parser.rs", "clap_builder__parser_parser.rs"),
            ("clap_builder-4.6.0/src/output/help_template.rs", "clap_builder__output_help_template.rs"),
            ("clap_builder-4.6.0/src/error/mod.rs", "clap_builder__error_mod.rs"),
        ),
    ),
)


CRATES_DOWNLOAD = "https://crates.io/api/v1/crates/{crate}/{version}/download"
SPARSE_INDEX = "https://index.crates.io/{shard}/{crate}"
USER_AGENT = "cntrdct-corpus-fetch/0.1 (https://github.com/ktrysmt/cntrdct)"


def http_get(url: str) -> Tuple[bytes, str]:
    """Return (body, final_url_after_redirects)."""
    req = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    with urllib.request.urlopen(req, timeout=60) as r:  # noqa: S310 — fixed-host
        return r.read(), r.url


def index_shard(crate: str) -> str:
    """The sparse-index sharding rule used by crates.io.
    1-char names live under 1/, 2-char under 2/, 3-char under 3/<first>/,
    and ≥ 4-char names under <first-2>/<chars-3-4>/."""
    n = len(crate)
    if n == 1:
        return "1"
    if n == 2:
        return "2"
    if n == 3:
        return f"3/{crate[0]}"
    return f"{crate[:2]}/{crate[2:4]}"


def lookup_index_cksum(crate: str, version: str) -> str:
    """Fetch the canonical SHA-256 ("cksum") for (crate, version) from
    https://index.crates.io. The response is JSON-lines, one entry per
    published version."""
    url = SPARSE_INDEX.format(shard=index_shard(crate), crate=crate)
    body, _ = http_get(url)
    for line in body.decode("utf-8").strip().split("\n"):
        if not line.strip():
            continue
        entry = json.loads(line)
        if entry.get("vers") == version:
            cksum = entry.get("cksum")
            if not cksum:
                raise RuntimeError(
                    f"index entry for {crate}=={version} has no cksum"
                )
            return cksum
    raise RuntimeError(
        f"version {version} not found in sparse index for crate {crate} "
        f"(checked {url})"
    )


def fetch_crate(entry: CorpusEntry) -> Tuple[bytes, str]:
    """Return (raw_tarball_bytes, final_download_url)."""
    declared = lookup_index_cksum(entry.crate_name, entry.version)
    body, final_url = http_get(
        CRATES_DOWNLOAD.format(crate=entry.crate_name, version=entry.version)
    )
    actual = hashlib.sha256(body).hexdigest()
    if actual != declared:
        raise RuntimeError(
            f"crate hash mismatch for {entry.crate_name}=={entry.version}: "
            f"index says {declared}, downloaded blob is {actual}"
        )
    return body, final_url


def extract_file(tarball: bytes, member_path: str) -> bytes:
    with tarfile.open(fileobj=io.BytesIO(tarball), mode="r:gz") as tf:
        try:
            f = tf.extractfile(member_path)
        except KeyError:
            f = None
        if f is None:
            raise RuntimeError(f"member not found in tarball: {member_path}")
        body = f.read()
    # Reject files that announce themselves as auto-generated. Such
    # files produce noise rather than signal in the cntrdct scan
    # (every method is structurally identical, so clone-drift fires
    # for every pair). A `// @generated` or `# @generated` marker in
    # the first 200 bytes is the de facto convention (syn, prost,
    # protobuf-rust, tonic, etc. all emit it).
    head = body[:200].lower()
    if b"@generated" in head:
        raise RuntimeError(
            f"member {member_path} carries an @generated marker; "
            "remove it from CORPUS or the resulting findings will "
            "be FPs by construction"
        )
    return body


def write_with_header(
    out_path: Path, body: bytes, source_url: str, license_spdx: str
) -> str:
    """Prepend a provenance header to `body` and write to `out_path`.
    Returns the SHA-256 of the written file (header + body).

    Rust line-comment syntax `//` is used so the cntrdct parser
    accepts the file. Mirroring the Python fetcher's `#` would
    produce a syntax error and the scanner would silently drop
    the file."""
    header = (
        f"// Source: {source_url}\n"
        f"// License: {license_spdx}\n"
        f"// Note: verbatim extract from upstream .crate\n"
        f"\n"
    )
    composed = header.encode("utf-8") + body
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_bytes(composed)
    return hashlib.sha256(composed).hexdigest()


def main(argv: List[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--out",
        default="benchmarks/wild-corpus",
        help="output directory (default: benchmarks/wild-corpus)",
    )
    parser.add_argument(
        "--manifest-skeleton",
        action="store_true",
        help=(
            "in addition to fetching files, write a manifest skeleton "
            "to <out>/manifest.skeleton.jsonl with empty `expected` arrays. "
            "Maintainer triages cntrdct findings into the real "
            "manifest.jsonl by hand."
        ),
    )
    args = parser.parse_args(argv[1:])

    out_root = Path(args.out)
    files_dir = out_root / "files"
    files_dir.mkdir(parents=True, exist_ok=True)

    skeleton: List[dict] = []
    for entry in CORPUS:
        print(f"fetching {entry.crate_name}=={entry.version}", file=sys.stderr)
        tarball, source_url = fetch_crate(entry)
        for member_path, flat_name in entry.files:
            try:
                body = extract_file(tarball, member_path)
            except RuntimeError as e:
                print(f"  skipping {flat_name}: {e}", file=sys.stderr)
                continue
            out_path = files_dir / flat_name
            sha = write_with_header(out_path, body, source_url, entry.license)
            print(f"  wrote files/{flat_name} sha256={sha[:12]}…", file=sys.stderr)
            skeleton.append(
                {
                    "file": f"files/{flat_name}",
                    "expected": [],
                    "source": source_url,
                    "license": entry.license,
                    "sha256": sha,
                }
            )

    if args.manifest_skeleton:
        skel_path = out_root / "manifest.skeleton.jsonl"
        with skel_path.open("w") as f:
            f.write(
                "// Manifest skeleton for the P-1 Rust wild corpus.\n"
                "// Generated by scripts/fetch_rust_corpus.py.\n"
                "// Maintainer fills in `expected: [...]` per file by\n"
                "// running `cntrdct scan` and triaging findings.\n"
            )
            for row in skeleton:
                f.write(json.dumps(row, sort_keys=True) + "\n")
        print(f"wrote {skel_path}", file=sys.stderr)

    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
